@server = http://localhost:5000

# @name getDiscovery
# call the discovery endpoint o the local server
GET {{server}}/.well-known/openid-configuration

@token_endpoint={{getDiscovery.response.body.$.token_endpoint}}
@userinfo_endpoint={{getDiscovery.response.body.$.userinfo_endpoint}}
###

# take some data from the client configuration and the user 
# for the calls below
# Inspect the clients in IdentityShell with 'Get-IdentityClient'
# Inspect the user in IdentityShell with Get-AspNetIdentityUser
@client_secret=secret
@client_id=client
@username=alice
@password=Pass123$
@scope=api1

# @name getResourceOwnerToken
# get the resource owner token
# request MUST be encoded as x-www-form-urlencoded
POST {{token_endpoint}}
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&scope={{scope}}
&grant_type=password
&username={{username}}
&password={{password}}
###
