@server = http://localhost:5000

###
# @name getDiscovery
# call the discovery endpoint o the local server
GET {{server}}/.well-known/openid-configuration

@token_endpoint={{getDiscovery.response.body.$.token_endpoint}}

###
# take some data from the client configuration for the calls below
# Inspect the clients in IdentityShell with 'Get-IdentityClient'
@client_secret=secret
@client_id=client
@client_allowed_scope=api1

###
# Example client
# request MUST be encoded as x-www-form-urlencoded
POST {{token_endpoint}}
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&scope={{client_allowed_scope}}
&grant_type=client_credentials


