@server = http://localhost:5000

###
# @name getDiscovery
# call the discovery endpoint o the local server
GET {{server}}/.well-known/openid-configuration

@device_authorization_endpoint={{getDiscovery.response.body.$.device_authorization_endpoint}}
@device_verification_uri={{getDiscovery.response.body.$.device_authorization_endpoint}}
@token_endpoint={{getDiscovery.response.body.$.token_endpoint}}

###
# take some data from the client configuration for the calls below
# Inspect the clients in IdentityShell with 'Get-IdentityClient'
@client_secret=secret
@client_id=client
@client_allowed_scope=api1

###
# @name getDeviceToken
# request a device authorization token
POST {{device_authorization_endpoint}}
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}

###
# the user code and the device code may server as input to the cmdlet of IdentityShell
# to inspact the operational store
@device_code={{getDeviceToken.response.body.$.device_code}}
@user_code={{getDeviceToken.response.body.$.user_code}}

###
# check if the token is already authenticated
POST {{token_endpoint}}
Content-Type:  application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:device_code
&client_id={{client_id}}
&client_secret={{client_secret}}
&device_code={{device_code}}


